"use strict";

module.exports = {
  USER_ROLES: ["OWNER", "ADMIN", "STAFF"],
  BUSINESS_STATUSES: ["ACTIVE", "SUSPENDED"],
  WHATSAPP_ACCOUNT_STATUSES: ["DISCONNECTED", "CONNECTED", "ERROR"],
  WEBHOOK_EVENT_STATUSES: ["RECEIVED", "PROCESSED", "FAILED", "DUPLICATE"],
  MESSAGE_DIRECTIONS: ["INBOUND", "OUTBOUND"],
  MESSAGE_STATUSES: ["QUEUED", "SENT", "DELIVERED", "READ", "FAILED"],
  CART_STATUSES: ["ACTIVE", "CONVERTED", "ABANDONED"],
  ORDER_STATUSES: [
    "NEW",
    "CONFIRMED",
    "PROCESSING",
    "READY",
    "OUT_FOR_DELIVERY",
    "DELIVERED",
    "COMPLETED",
    "CANCELLED",
    "DELIVERY_FAILED",
    "RETURNED",
    "CUSTOMER_NOT_REACHABLE",
  ],
  PAYMENT_METHODS: ["COD"],
  PAYMENT_STATUSES: ["PENDING", "COLLECTED", "FAILED", "CANCELLED"],
  ACTOR_TYPES: ["USER", "SYSTEM", "CUSTOMER"],
  INVENTORY_MOVEMENT_REASONS: [
    "ORDER_CONFIRM",
    "ORDER_CANCEL_RESTORE",
    "ORDER_RETURN_RESTORE",
    "ADJUSTMENT",
    "MANUAL_SET",
  ],
};
